#!/bin/bash

# Anaconda
function install_anaconda {
	# Variables
	NAME="Anaconda"
  	# Install
	echo_message info "Installing $NAME..."
	\curl -s https://repo.anaconda.com/archive/Anaconda3-5.3.1-Linux-x86_64.sh | bash -s "-d"
	 fish -c "set -U fish_user_paths ~/anaconda3/bin \$fish_user_paths"
	# Done
	echo_message success "Installation of $NAME complete."
	whiptail --title "Finished" --msgbox "Installation of $NAME complete." 8 56
	thirdparty
}
